### ISSUE TITLE
Remove datasets from git repo and strip from history

### ISSUE THREAD

**Issue by willfleury** [ThinkBigAnalytics/AoaDemoModels#111]
remove this and clean history so the repo is small 

https://github.com/ThinkBigAnalytics/AoaDemoModels/tree/master/model_definitions/b1e18b12-5ccd-4c94-b96b-c2cebf230150/notebooks/Datasets

Careful on this.. I'm not sure what happens with the core clone if you strip / rewrite history.. Will you need to restart the pod (if we have efs fix in place then we need to wipe the git dir first),

**Comment by Christian-TD** [comment]
@willfleury @dartov @sheheryartd finally managed to remove the datasets from the history, and seems fine. Pushed it to a temp repo for you to check https://github.com/Christian-TD/AoaDemoModels before forcibly pushing to master. Zipped master branch from the fixed repo is about 916Kb and the original is about 6 Mb

**Comment by willfleury** [comment]
Cool! The non-zipped versions have a much larger difference! 

Merge away. To validate the core change, merge the core change first and wait for it to be deployed to master. Then merge this and you'll need to also manually bounce the core in demo as it will need to clone the repos after this as it will break (as the core change won't be available there)

**Comment by Christian-TD** [comment]
> Cool! The non-zipped versions have a much larger difference!
> 
> Merge away. To validate the core change, merge the core change first and wait for it to be deployed to master. Then merge this and you'll need to also manually bounce the core in demo as it will need to clone the repos after this as it will break (as the core change won't be available there)

Ok, but I might need you to temporarily disable the lock to push --force to master, it's the only way to rewrite the whole master branch.

**Comment by Christian-TD** [comment]
Done, if you experience issues when pulling in local repo, abort and do a `git pull --rebase`
