### ISSUE TITLE
Remove pyspark example

### ISSUE THREAD

**Issue by willfleury** [ThinkBigAnalytics/AoaDemoModels#122]
@dartov @Christian-TD what do you think? I think we should remove support in the core for it also. I can't see a realistic scenario we would support this now.

**Comment by Christian-TD** [comment]
> @dartov @Christian-TD what do you think? I think we should remove support in the core for it also. I can't see a realistic scenario we would support this now.

I would leave it for now, as it doesn't harm while it does not require updates or maintenance for now. But from the 'marketing' perspective, it showcases that AOA integrates easily with the most common frameworks. I think it's a good feature to have in the products 'brochure'.

**Comment by willfleury** [comment]
Lets discuss but I think we need to remove.. We don't support it anymore, i'm not sure when it was tested last and even the example code doesn't really use pyspark.. Like we are doing with other areas in the back, lets reduce our scope to what we will support well and try and reduce our maintenance burden.

closing in #124
